"""Apply the light-engine wiring to web/app/room.js (the worker-engine version, 2026-10-02+). Idempotent; asserts each anchor.
Usage: python patch_room.py [path/to/room.js] [--check]"""
import sys
path = next((a for a in sys.argv[1:] if not a.startswith("--")), "web/app/room.js"); check = "--check" in sys.argv
s = open(path).read(); n = 0
REPS = [
 ("import { Engine } from '../lib/engine/client.js';", "import { Engine } from '../lib/engine/client.js';\nimport { LightEngine } from '../lib/engine/light.js';\nimport { mountDebugLine, memoryInfo } from './debugline.js';\nimport { installRemoteLog, rlog } from '../lib/rlog.js';"),
 ("let safeMode = params.get('safe') === '1' || (lastBoot === 'loading' || lastBoot === 'painting');\nif (safeMode) localStorage.setItem('vqpaint.crashes', String((+localStorage.getItem('vqpaint.crashes') || 0) + 1));",
  "const crashedLastTime = lastBoot === 'painting';   // a reload while the brush was loading or painting; a visit that only viewed never counts\nconst CRASH_KEY = 'vqpaint.crashes.v2';   // versioned: counters from before the loader fix are ignored\nif (crashedLastTime) localStorage.setItem(CRASH_KEY, String((+localStorage.getItem(CRASH_KEY) || 0) + 1));\nif (params.get('reset') === '1') localStorage.setItem(CRASH_KEY, '0');\nconst crashes = +localStorage.getItem(CRASH_KEY) || 0;\nlet safeMode = params.get('safe') === '1';   // light engine: a crash -> lightest mode (+ a calm 'try anyway'); waiting for a computer only when even the lightest mode cannot load\nconst lightest = params.get('light') === '1' || crashes >= 1;"),
 ("sessionStorage.setItem('vqpaint.boot', 'loading');\nconst lowMem", "sessionStorage.setItem('vqpaint.boot', 'view');\nconst lowMem"),
 ("const lowMem = isPhone || safeMode || params.get('lowmem') === '1';", "const lowMem = isPhone || safeMode || params.get('lowmem') === '1';\nlet useTiny = params.get('engine') !== 'ort';   // the light engine (tiny decoder + MobileCLIP as WebGL2 shaders, no ONNX Runtime) is the default on every device; ?engine=ort forces the ONNX worker"),
 ("const engine = new Engine();", "const logUrl = params.get('log') === '0' ? null : `${CONFIG.roomsUrl}/room/${roomId}/log`;\ninstallRemoteLog({ url: logUrl, tag: 'page' }); rlog({ t: 'boot', crashes, lastBoot, lightest, safeMode, lowMem, isPhone });\nlet engine = new Engine(), lightCfg = null, brushFailed = false;"),
 ("function canPaintHere() { if (forceNoPaint || safeMode || engine.broken) return false; if (!lowMem) return true;", "function canPaintHere() { if (forceNoPaint || safeMode || engine.broken || brushFailed) return false; if (useTiny) return true; if (!lowMem) return true;"),
 ("if (helpersOn && (forceNoPaint || lowMem || !caps.gpu) && (bestHelper()", "if (helpersOn && (forceNoPaint || (!useTiny && (lowMem || !caps.gpu))) && (bestHelper()"),
 ("if (h && (forceNoPaint || lowMem || !caps.gpu)) return requestReaction(", "if (h && (forceNoPaint || (!useTiny && (lowMem || !caps.gpu)))) return requestReaction("),
 ("margin: MARGIN,", "margin: useTiny ? 2 : MARGIN,"),
 ("if (lowMem) await releaseBrush();", "if (lowMem && !useTiny) await releaseBrush();"),
 ("    stats.strokes++; stats.strokeSeconds.push(secs); stats.lastTries = res.steps; stats.lastStatus = `${res.steps} tries in ${secs.toFixed(1)}s`;", "    stats.strokes++; stats.strokeSeconds.push(secs); stats.lastTries = res.steps; stats.lastStatus = `${res.steps} tries in ${secs.toFixed(1)}s`; rlog({ t: 'stroke', tries: res.steps, sec: +secs.toFixed(1), score: +(res.score || 0).toFixed(3), crop: `${res.crop.w}x${res.crop.h}`, decodeMs: stats.fullDecodeMs });"),
 ("    loading.set(t('load.brush', { pct: 0 })); setStage('engine');\n    const r = await engine.init({ modelBase: M,", "    loading.set(t('load.brush', { pct: 0 })); setStage('engine'); rlog({ t: 'brush', step: 'start', engine: stats.engine, mode: stats.engineMode });\n    const initEngine = () => engine.init({ logUrl, modelBase: M,"),
 ("    decoder = engine.decoder; clip = engine.clip; painter = engine.painter; ep = r.ep; caps.speed = stats.fullDecodeMs = r.speed;",
  "    let r;\n    try { r = await initEngine(); }\n    catch (e) {   // the light engine in a worker failed (OffscreenCanvas/WebGL2 quirks or a lost error): once more on the page thread, then a clear message\n      rlog({ t: 'brush', step: 'init-failed', engine: stats.engine, error: String(e && e.message).slice(0, 300) });\n      if (useTiny && stats.engine === 'tiny-worker') { try { engine.terminate(); } catch (_) {} engine = new LightEngine(lightCfg); stats.engine = 'tiny'; loading.set(t('load.brush', { pct: 0 })); r = await initEngine(); }\n      else throw e;\n    }\n    rlog({ t: 'brush', step: 'ready', engine: stats.engine, variant: r.variant, speed: r.speed, ep: r.ep });\n    decoder = engine.decoder; clip = engine.clip; painter = engine.painter; ep = r.ep; caps.speed = stats.fullDecodeMs = r.speed; if (r.variant) stats.engineVariant = r.variant;"),
 ("    loading.hide(); sessionStorage.setItem('vqpaint.boot', 'ok');\n  })().finally(() => { ensuring = null; });", "    loading.hide(); sessionStorage.setItem('vqpaint.boot', 'ok');\n  })().catch((e) => {   // never a pill stuck at a number: hide it, say what happened, and do not count this as a crash\n    loading.hide(); sessionStorage.setItem('vqpaint.boot', 'error'); mode = 'view';\n    const msg = /WebGL2/i.test(String(e && e.message)) ? t('status.noWebgl') : t('status.brushFailed', { error: String(e && e.message).slice(0, 120) });\n    setStatus(msg, 10000); rlog({ t: 'brush', step: 'failed', error: String(e && e.message).slice(0, 300) });\n    brushFailed = true; try { toast.message(`${msg}<br><br><button class=\"pill\" data-try>${t('msg.tryAnyway')}</button>`); const m = document.querySelector('[data-message]'); m.querySelector('[data-try]').onclick = () => { m.hidden = true; brushFailed = false; engine.broken = null; ensureBrush().catch(() => {}); }; } catch (_) {}\n    throw e;\n  }).finally(() => { ensuring = null; });"),
 ("  if (!lowMem && !forceNoPaint && params.get('preload') === '1') await ensureBrush();", "  const conn = navigator.connection || {}; const saveData = !!conn.saveData || /(^|-)2g$/.test(conn.effectiveType || '');\n  if (!forceNoPaint && !safeMode && params.get('preload') !== '0' && !saveData) setTimeout(() => { if (!painter && !ensuring) ensureBrush().catch(() => {}); }, 1200);   // the brush loads in the background so the first stroke starts right away (not on data saver / 2G)"),
 ("  beacon('gpu', { gpu }); caps.gpu = !!gpu;", "  beacon('gpu', { gpu }); caps.gpu = !!gpu;\n  lightCfg = lightest ? { mode: 'clip', clip: 'clip_vision_i8', scorer: null, text: 'S' } : { mode: params.get('mode') || 'prefilter' };\n  const workerLight = useTiny && params.get('lightworker') !== '0' && Engine.canHostLight();   // the light engine in a worker when the browser allows (page frames stay free); on the page thread otherwise (iOS 15/16)\n  if (useTiny && workerLight) { engine = new Engine({ light: lightCfg }); stats.engine = 'tiny-worker'; stats.engineMode = lightest ? 'lightest (int8 CLIP, no scorer)' : (params.get('mode') || 'prefilter'); }\n  else if (useTiny) { engine = new LightEngine(lightCfg); stats.engine = 'tiny'; stats.engineMode = lightest ? 'lightest (int8 CLIP, no scorer)' : (params.get('mode') || 'prefilter'); }\n  mountDebugLine($('roombar'), () => { const secs = stats.strokeSeconds[stats.strokeSeconds.length - 1]; return { engine: (stats.engine || 'ort') + (stats.engineVariant ? ' ' + stats.engineVariant : ''), mode: stats.engineMode || ep || '-', crashes, 'last stroke': secs ? `${stats.lastTries} tries in ${secs.toFixed(1)} s (${(stats.lastTries / secs).toFixed(1)}/s)` : '-', 'decode ms': stats.fullDecodeMs ?? '-', memory: memoryInfo() }; });"),
 ("  caps.helper = !!gpu && !lowMem && !forceNoPaint && helpersOn;", "  caps.helper = (useTiny || !!gpu) && !lowMem && !forceNoPaint && helpersOn;"),
]
missing = []
for a, b in REPS:
    if b in s: continue
    c = s.count(a)
    if c == 0: missing.append(a[:70]); continue
    s = s.replace(a, b); n += c
if check: print(f"{len(REPS) - len(missing)}/{len(REPS)} anchors found"); [print("  missing:", m) for m in missing]; sys.exit(1 if missing else 0)
if missing: sys.exit("anchors not found: " + " | ".join(missing))
open(path, "w").write(s); print(f"room.js: {n} edits applied")
